/*Write a program that will read a positive integer and determine and print its binary equivalent.
(Hint: The bits of binary representation of an integer can be generated by repeatedly dividing
the number and the successive quotients by 2 and saving the remainder, which is either 0 or 1,
after each division. )
*/

#include <stdio.h>

int main() {
    int number;
    int arr[20];
    int i = 0;

    printf("Enter a number to be converted to binary: ");
    scanf("%d", &number);

    while (number != 0) { // Changed the condition to check if the number is not zero
        arr[i] = number % 2;
        number = number / 2;
        i++;
    }

    printf("Binary representation: ");
    if (i == 0) { // Special case for input 0
        printf("0");
    }
    else {
        for (int j = i - 1; j >= 0; j--) {
            printf("%d", arr[j]);
        }
    }
    printf("\n");
    return 0;
}